# Stage 1: Build Angular
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --production=false
COPY . .
RUN npx ng build --configuration=production

# Stage 2: Servir con Nginx
FROM nginx:alpine

COPY --from=builder /app/dist/melotune/browser /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
